# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x79EQXkG8iLpuswi5iVTXJ5TlwUdaJjt
"""

from transformers import pipeline, AutoModelForQuestionAnswering, AutoTokenizer

# Özel bir model ve tokenizer seçmek isterseniz burada belirleyebilirsiniz
model_name = "distilbert-base-uncased-distilled-squad"
model = AutoModelForQuestionAnswering.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

question_answerer = pipeline("question-answering", model=model, tokenizer=tokenizer)

while True:

  # Kullanıcıdan ismini al
  name = input("Adınız nedir? ")

  # Kullanıcıdan yapay zeka hakkında bilgi almak istediğini yazmasını iste
  request = input(f"Merhaba {name}, yapay zeka hakkında bilgi almak istiyor musunuz? (Evet/Hayır): ")

  if request.lower() == "evet":
      # Kullanıcıdan yapay zeka ile ilgili soru al
      if request.lower() == "evet" or request.upper() == "Evet":
        print("Yapay zeka, makinelerin insan benzeri zeka işlevlerini yerine getirmesine olanak tanıyan bir alandır. "
            "Bu, öğrenme, planlama, problem çözme ve veri analizi gibi yetenekleri içerir. "
            "Son yıllarda yapay zeka, derin öğrenme ve büyük veri kullanımının artmasıyla önemli bir gelişme yaşamıştır. "
            "Yapay zeka, otomasyon, tıp, ulaşım, hizmet sektörü ve daha birçok alanda büyük bir etki yaratmaktadır.")

      # Soruyu cevapla
      result = question_answerer(question=request, context="Yapay zeka hakkında genel bir bilgilendirme.")


  request2 = input(f"Merhaba {name},Dunya nufusu hakkında bilgi almak istiyor musunuz? (Evet/Hayır): ")

  if request2.lower() == "evet" or request2.upper() == 'Evet':
      if request2.lower() == "evet" or request2.upper() == "Evet":
          print("Dünya nüfusu, gezegenimizdeki insanların toplam sayısını ifade eder. 2021 itibariyle dünya nüfusu yaklaşık olarak 7.9 milyar insanı aşmıştır. Nüfus, coğrafi bölgelere, ülkelere ve kıtalara göre farklılık gösterir. Örneğin, Çin ve Hindistan gibi büyük nüfusa sahip ülkeler, dünya nüfusunun büyük bir bölümünü temsil eder. Ayrıca, dünya nüfusu sürekli olarak artmaktadır, bu da kaynak kullanımı, gıda güvenliği ve çevresel sürdürülebilirlik gibi küresel sorunları gündeme getirir. Dünya nüfusu, demografi ve insan coğrafyası çalışmalarının önemli bir konusudur ve nüfusun büyüklüğü ve bileşimi, birçok toplumsal, ekonomik ve siyasi sorunu etkileyebilir.")
  result2 = question_answerer(question=request2, context="Yapay zeka hakkında genel bir bilgilendirme.")

  cikis = input("eger baska bir sorunuz yok ise lutfen q tusuna basiniz...")
  if cikis == "q":
    break
  # Cevabı ekrana yazdır
  print(f"Cevap: '{result['answer']}', skor: {round(result['score'], 4)}")
  print(f"Cevap: '{result2['answer']}', skor: {round(result2['score'], 4)}")
else:
  print("Anladım, herhangi bir başka sorunuz veya yardım ihtiyacınız olursa lütfen bana sormaktan cekinmeyiniz. Iyi gunler.")